import { ReactNode } from 'react';
import Head from 'next/head';
import Footer from './footer';
import NavBar from './navbar';



export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};


interface LayoutProps {
  children: ReactNode;
}

const Layout: React.FC<LayoutProps> = ({ children }) => {
  return (
    <>
      <Head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </Head>

      <NavBar />

      <main>{children}</main>

      <Footer />
    </>
  );
};

export default Layout;
